apiVersion: v1
kind: Service
metadata:
  name: print-hello-world-svc
  labels:
    name: print-hello-world-svc
    app: demo-hello-world-app
spec:
  type: NodePort
  selector:
    name: print-hello-world
    app: demo-print-hello-world
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30004
